# netlify.toml

[build]
  # Comando para construir seu site Next.js
  command = "npm run build"
  
  # Diretório onde o site construído será publicado
  publish = ".next"

[[plugins]]
  # Plugin essencial da Netlify para sites Next.js
  package = "@netlify/plugin-nextjs"
